#ifndef MQTT_CLIENT_C_INTEGRATION_TESTS_CONFIG_H
#define MQTT_CLIENT_C_INTEGRATION_TESTS_CONFIG_H


#define CONNECT_MAX_ATTEMPT_COUNT 3

#define PUBLISH_COUNT 100

#define INTEGRATION_TEST_TOPIC "Tests/Integration/C"

#endif //MQTT_CLIENT_C_INTEGRATION_TESTS_CONFIG_H
