#ifndef SRC_PROTOCOL_MQTT_PAHO_EMBEDDEDC_PLATFORM_LINUX_HOSTNAME_COMPARE_H_
#define SRC_PROTOCOL_MQTT_PAHO_EMBEDDEDC_PLATFORM_LINUX_HOSTNAME_COMPARE_H_

#define CURL_HOST_MATCH 1
#define CURL_HOST_NOMATCH 0

int hostmatch(const char *hostname, const char *pattern);

#endif /* SRC_PROTOCOL_MQTT_PAHO_EMBEDDEDC_PLATFORM_LINUX_HOSTNAME_COMPARE_H_ */
